[colors.primary]
background = '#121318'
foreground = '#e3e1e9'

[colors.selection]
text = '#e3e1e9'
background = '#354479'

[colors.cursor]
text = '#121318'
cursor = '#b6c4ff'

[colors.normal]
black   = '#121318'
red     = '#e44e45'
green   = '#6ed66f'
yellow  = '#dbd47b'
blue    = '#6c7bdc'
magenta = '#939bbf'
cyan    = '#b6c4ff'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e0625f'
green   = '#86e086'
yellow  = '#e8e297'
blue    = '#c3d2ff'
magenta = '#5b79b6'
cyan    = '#7272ba'
white   = '#ffffff'
